### ISSUE TITLE
Dockerized version

### ISSUE THREAD

**Issue by xaviervia** [possatti/pokemonsay#4]
Just wanted to let you know that I dockerized this in https://github.com/xaviervia/docker-pokemonsay . It was the simplest way of having it working in any *nix .

**Comment by possatti** [comment]
Very nice. I couldn't manage to install docker to try it. It seems a 64 bit OS is needed. Nonetheless, I liked it very much. :+1:

**Comment by possatti** [comment]
I also wrote about it on the [README.md](https://github.com/possatti/pokemonsay/blob/master/README.md) in the _Install_ section. So people have one more option for installing it.

Thanks buddy.

**Comment by xaviervia** [comment]
Thank you for making this ;)
